name: Blog Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    defaults:
      run:
        working-directory: ./backend
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './backend/package-lock.json'
      
      # Install system dependencies for MongoDB Memory Server
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl1.1
        working-directory: ./
      
      - name: Install dependencies
        run: npm install
      
      - name: Run linter on backend
        run: npm run lint
      
      - name: Run backend tests
        run: npm test
        env:
          # Set MongoDB Memory Server to use system binary
          MONGOMS_DOWNLOAD_URL: https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2004-6.0.2.tgz
          MONGOMS_VERSION: 6.0.2