name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.deploy-frontend.outputs.url }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          service_account: ${{ secrets.GOOGLECLOUD_SERVICE_ACCOUNT }}
          credentials_json: ${{ secrets.GOOGLECLOUD_CREDENTIALS }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/blog-backend:latest
      
      - id: deploy-backend
        name: Deploy backend to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: blog-backend
          image: ${{ secrets.DOCKERHUB_USERNAME }}/blog-backend:latest
          region: ${{ secrets.GOOGLECLOUD_REGION }}
      
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/blog-frontend:latest
          platforms: linux/amd64,linux/arm64
          build-args: VITE_BACKEND_URL=${{ steps.deploy-backend.outputs.url }}/api/v1
      
      - id: deploy-frontend
        name: Deploy frontend to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: blog-frontend
          image: ${{ secrets.DOCKERHUB_USERNAME }}/blog-frontend:latest
          region: ${{ secrets.GOOGLECLOUD_REGION }}